### ISSUE TITLE
CLUSTERDOWN

### ISSUE THREAD

**Issue by splitice** [vishnudxb/redis-cluster#1]
This action is the most common cause of failures for us, with approx 1/20 runs resulting in a failure due to CLUSTERDOWN

Not sure if its a race condition or what (Investigating) it seems to be pretty late in the unit tests so I suspect not

**Comment by splitice** [comment]
Looking into it I suspect the problem is the massively short cluster timeout configured. Its too short for long running ops at only 10ms.

**Comment by vishnudxb** [comment]
@splitice  Can we use a [timeout-minutes ](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepstimeout-minutes) in the gh action? Please note there are some [limits](https://stackoverflow.com/questions/68187987/github-actions-job-timeout)

**Comment by splitice** [comment]
This is probably the fix: https://github.com/vishnudxb/docker-redis-cluster/compare/master...X4BNet:docker-redis-cluster:master

I'll be able to verify over the next few weeks worth of runs.

**Comment by vishnudxb** [comment]
@splitice  Thank you, I merged your pr

**Comment by splitice** [comment]
My patch looks to have fixed the issue. Did over 40 CI runs and no repeats of this issue.

**Comment by gaby** [comment]
@splitice @vishnudxb I'm running into the same issue, most of our CI jobs are randomly failing. What's the difference between this repo and https://github.com/vishnudxb/docker-redis-cluster ?

This one doesnt have any updates since 2020, while the other has recent updates

**Comment by gaby** [comment]
What's the actual fix? Can you provide an example yaml. Thanks!

**Comment by splitice** [comment]
https://github.com/vishnudxb/docker-redis-cluster/commit/2eb13ca26d61f02714fae58f39193e3ac250c220

The fix which was merged in 2023.

**Comment by gaby** [comment]
@splitice We just had our redis cluster fail multiple times in a row *today*. And this a test at the end of the CI.

We are using this:

```yaml
            -   name: Setup Redis Cluster
                uses: vishnudxb/redis-cluster@1.0.5
                with:
                    master1-port: 7000
                    master2-port: 7001
                    master3-port: 7002
                    slave1-port: 7003
                    slave2-port: 7004
                    slave3-port: 7005
```
